### ISSUE TITLE
Error on small HybISS data set

### ISSUE THREAD

**Issue by massaraneko** [hubmapconsortium/spatial-transcriptomics-pipeline#35]
Hello, 
I am excited because you have provided a very excellent pipeline of spatial transcriptomes. As you have mentioned, the spatial transcriptome analysis environment has limited standardization of documentation and methods, making it very difficult for researchers who are just starting out.

Currently I am facing the following problems and would be very grateful if you could give me some valid advice.

I prepared the simplest data to begin my analysis of the HybISS experiment. It is 1 FOV (1900x1900 pixel, 8000 spots, 100 cells), 2 rounds, 3 channels, 1 Z plane, and 9 genes. When I run PIPEFISH (Aug 10 version) on this set, it fails in the 4_Decoded process. The log is below.

4_Decoded\20230823_0256_starfish_runner.log

```
Coordinates:
  * target   (target) object 'egr' 'Act5C' 'Cdk1' 'E2f1' ... 'pxb' 'rho' 'Tollo'
  * r        (r) int64 0 1
  * c        (c) int64 0 1 2, 'decoderKwargs': {}, 'callableDecoder': <class 'starfish.core.spots.DecodeSpots.postcode.postcodeDecode'>, 'n_processes': None}
Traceback (most recent call last):
  File "/opt/starfishDriver.py", line 1142, in <module>
    compositeKwargs,
  File "/opt/starfishDriver.py", line 831, in run
    output_name=f"{output_dir}spots/composite_",
  File "/opt/starfishDriver.py", line 173, in blobDriver
    decoded = decodeRunner(blob, codebook, **decodeRunnerKwargs)
  File "/opt/starfishDriver.py", line 114, in decodeRunner
    results = decoder.run(spots=spots)
  File "/starfish/starfish/core/pipeline/algorithmbase.py", line 23, in helper
    result = func(*args, **kwargs)
  File "/starfish/starfish/core/spots/DecodeSpots/postcode.py", line 37, in run
    out = decoding_function(spots_s, barcodes_01, print_training_progress=True)
  File "/starfish/starfish/core/spots/DecodeSpots/postcode_funcs.py", line 241, in decoding_function
    torch.tensor((1 - alpha) / codes_inf.shape[0]).repeat(codes_inf.shape[0])))
ZeroDivisionError: float division by zero

```
Strangely enough, if I reduce the number of genes in the barcode file from 9 to 4, it runs without error to the end; there is no commonality in the 4 genes and it works if I replace them, but 5 causes an error.

```
Coordinates:
  * target   (target) object 'ct' 'pxb' 'rho' ... 'blank3' 'blank1' 'blank4'
  * r        (r) int64 0 1
  * c        (c) int64 0 1 2, 'decoderKwargs': {}, 'callableDecoder': <class 'starfish.core.spots.DecodeSpots.postcode.postcodeDecode'>, 'n_processes': None}
decodeRunner 0.7879128456115723
Saved decoded csv file tmp/tVW6HYYQ4H/4_Decoded/csv/composite_decoded.csv.
Saved cdf file tmp/tVW6HYYQ4H/4_Decoded/cdf/composite_decoded.cdf
spots saved.
Saved decoded csv file tmp/tVW6HYYQ4H/4_Decoded/csv/fov_000_decoded.csv.
Saved cdf file tmp/tVW6HYYQ4H/4_Decoded/cdf/fov_000_decoded.cdf
Saved decoded csv file tmp/tVW6HYYQ4H/4_Decoded/csv/fov_001_decoded.csv.
Saved cdf file tmp/tVW6HYYQ4H/4_Decoded/cdf/fov_001_decoded.cdf
Saved decoded csv file tmp/tVW6HYYQ4H/4_Decoded/csv/fov_002_decoded.csv.
Saved cdf file tmp/tVW6HYYQ4H/4_Decoded/cdf/fov_002_decoded.cdf

```

Thinking that request #34 may be related to this problem, I tried running it with the latest PIPEFISH (Sep 6 version) that has been merged it, but this time the error occurs regardless of the number of genes (9 or 4).

4_Decoded\20230908_0809_starfish_runner.log

```
Coordinates:
  * target   (target) object 'egr' 'Act5C' 'Cdk1' ... 'blank0' 'blank3' 'blank4'
  * r        (r) int64 0 1
  * c        (c) int64 0 1 2, 'decoderKwargs': {}, 'callableDecoder': <class 'starfish.core.spots.DecodeSpots.postcode.postcodeDecode'>, 'n_processes': None}
Traceback (most recent call last):
  File "/opt/starfishDriver.py", line 1155, in <module>
    compositeKwargs,
  File "/opt/starfishDriver.py", line 844, in run
    output_name=f"{output_dir}spots/composite_",
  File "/opt/starfishDriver.py", line 173, in blobDriver
    decoded = decodeRunner(blob, codebook, **decodeRunnerKwargs)
  File "/opt/starfishDriver.py", line 114, in decodeRunner
    results = decoder.run(spots=spots)
  File "/starfish/starfish/core/pipeline/algorithmbase.py", line 23, in helper
    result = func(*args, **kwargs)
  File "/starfish/starfish/core/spots/DecodeSpots/postcode.py", line 37, in run
    out = decoding_function(spots_s, barcodes_01, print_training_progress=True)
  File "/starfish/starfish/core/spots/DecodeSpots/postcode_funcs.py", line 169, in decoding_function
    codes = torch.cat((codes, torch.zeros(1, D)))
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 6 but got size 4 for tensor number 1 in the list.

```
The iss_metadata.json is basically the same as the demo file (iss_mouse_brain), but the latest version of PIPEFISH requires the value of "aux_single_round", so the following is added.

	"aux_tilesets": {
		"aux_single_round": ["false"],
		
The iss_mouse_brain demo file works fine in the latest version by adding the following, so I don't think there is a problem with the software runtime environment.

		"aux_single_round": ["false","false"],

Thanks!

**Comment by nickeener** [comment]
Hey @massaraneko, thanks for your interest in our tool! I'm actually not totally sure what's going on here, I don't think it's related to the PR you mentioned as that PR was a change to the intensity rescaling operation which, if you're using the unedited iss_metadata.json file from the demo inputs, shouldn't be run at all. If you could share your inputs (the metadata.json, pipeline.yml, codebook file (csv or json), and the raw image files for a single FOV) I can probably track down exactly what's going wrong. You could upload them to google drive or a similar service if you prefer and just share the link here so we can access them.

**Comment by massaraneko** [comment]
> Hey @massaraneko, thanks for your interest in our tool! I'm actually not totally sure what's going on here, I don't think it's related to the PR you mentioned as that PR was a change to the intensity rescaling operation which, if you're using the unedited iss_metadata.json file from the demo inputs, shouldn't be run at all. If you could share your inputs (the metadata.json, pipeline.yml, codebook file (csv or json), and the raw image files for a single FOV) I can probably track down exactly what's going wrong. You could upload them to google drive or a similar service if you prefer and just share the link here so we can access them.

**Comment by massaraneko** [comment]
Hi @nickeener, thanks for the suggestions.

Here is the set of files.
https://drive.google.com/file/d/1n_VnphVOEzStotPugzOLjzftCkFOTzgY/view?usp=drive_link

I would be happy if this data could provide some information that leads to a solution.

**Comment by massaraneko** [comment]
Thank you for your detailed explanation. Since we started with the smallest configuration for this trial experiment, I understood that the lack of space in the codebook and the blank space would not fit the algorithm in the software. Our experimental plan is to expand the number of genes to the normal scale, but I think it will be useful for other users to be able to analyze even the current small data.

**Comment by nickeener** [comment]
@massaraneko I think we've fixed the problem so go ahead and update the docker image/git repo and try it again. It will still fail on the test dataset you gave me as it uses up the entire codebook space without any blank codes but if you try it on an experiment that either doesn't use the entire codebook space or has some blank barcodes in the codebook (or both) it should work. Thanks for pointing out this issue to us. Now that postcode is no longer optimizing for blank barcodes the results we get from our test dataset are now slightly better (1% more true decoded targets, and almost half as many decoded blank barcodes!).

**Comment by nickeener** [comment]
@massaraneko haven't heard from you so I'm assuming your issue was resolved and will be closing this issue.
