### ISSUE TITLE
barcodeBuildFunc modifies external variables

### ISSUE THREAD

**Issue by guoyang-github** [hubmapconsortium/spatial-transcriptomics-pipeline#49]
Dear developers,
Thanks for creating such a useful tool. I have been using the CheckAll decoding method and noticed a piece of code related to the modification of external variables within the barcodeBuildFunc function.

```
def barcodeBuildFunc(allNeighbors: list, currentRound: int, roundOmitNum: int, roundNum: int) -> list:
    
    allSpotCodes = []

    for neighbors in allNeighbors:
        neighborLists = [neighbors[rnd] for rnd in range(roundNum)]
        if roundOmitNum > 0:
            [neighbors[rnd].append(0) for rnd in range(roundNum)]
        codes = list(product(*neighborLists))
```

In the current implementation of barcodeBuildFunc, the function modifies the neighbors object, which refers to an external variable, and in turn affects upstream variables neighborLists. I'm not sure whether it will lead to unintended side effects. If I change the code to the following form, I wonder if it makes sense?

```
def barcodeBuildFunc_revised(allNeighbors: list, currentRound: int, roundOmitNum: int, roundNum: int) -> list:
    
    allSpotCodes = []

    for neighbors in allNeighbors:
        if roundOmitNum > 0:
            neighbors = [neighbors[rnd] + [0] for rnd in range(roundNum)]
        neighborLists = [neighbors[rnd] for rnd in range(roundNum)]
        codes = list(product(*neighborLists))
```

The permalink to the code:
https://github.com/spacetx/starfish/blob/master/starfish/core/spots/DecodeSpots/check_all_funcs.py

Thanks for your help.

**Comment by nickeener** [comment]
Sorry for the long delay in responding. Thanks for bringing this to our attention. It has been fixed with ctcisar/starfish#25 and we've done some testing and found that it didn't have any affect on the decoded results but still good to have proper scope etiquette in our code.
