### ISSUE TITLE
PIPEFISH on MERFISH example dataset - execution fails during starfishDriver.py 

### ISSUE THREAD

**Issue by loreseeker** [hubmapconsortium/spatial-transcriptomics-pipeline#58]
Hello, 

I have tried to run PIPEFISH 3.3 on the example MERFISH dataset provided, [merfish_human_u2os.tar.gz](https://zenodo.org/records/7647746/files/merfish_human_u2os.tar.gz?download=1) with cwltool 3.1.20240112164112 (local command line: cwltool spatial-transcriptomics-pipeline-master/pipeline.cwl merfish_human_u2os/pipeline.yml), however the workflow fails during starfish execution (log attached)
[20240418_115023.882341_starfish_runner.log](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/files/15024533/20240418_115023.882341_starfish_runner.log)

Running this input dataset with PIPEFISH 2.61 and the same version of cwltool completes successfully.

**Comment by ctcisar** [comment]
Hello!
Given the error in this file, it appears that you using the (unstable) `:master` release, and are not actually using PIPEFISH v3.3, the most recent `:release` version.

Please re-download the repo with `git clone -b release https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline.git` and ensure that `pipeline.cwl` contains the line `dockerPull: hubmap/starfish-custom:3.3`

Thank you for bringing this error to our attention, we will be sure to address it before making the next update to `:release`.

**Comment by loreseeker** [comment]
Hello!

You are right, it was my mistake, I was using the latest Docker image and code. Thank you for your help, running the 3.3 release worked.

**Comment by loreseeker** [comment]
Hi, just to note for a future release, while the MERFISH example completes successfully with the PIPEFISH release 3.3 code and Docker, SEQFISH example (seqfish_mouse_embryo) does not (starfish_runner log attached, same cwltool version). Please feel free to close this issue if this is expected.

[20240419_151337.953684_starfish_runner.log](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/files/15044916/20240419_151337.953684_starfish_runner.log)

**Comment by ctcisar** [comment]
Thanks for bringing these issues to our attention, they should be fixed as of v3.4, the latest `:release` version. We have added some tests to our release process to keep incompatibility issues with our sample datasets from cropping up again.
